CREATE TABLE bronx_sales_prices (
     BOROUGH TEXT NOT NULL,
     NEIGHBORHOOD VARCHAR NOT NULL,
	 BUILDING_CLASS_CATEGORY VARCHAR NOT NULL,
	 NUMBER_OF_SALES INT NOT NULL,
	 MINIMUM_SALE_PRICE INT NOT NULL,
	 AVERAGE_SALE_PRICE INT NOT NULL,
	 MEDIAN_SALE_PRICE INT NOT NULL,
	 MAXIMUM_SALE_PRICE INT NOT NULL
);


CREATE TABLE brookyln_sales_prices (
     BOROUGH TEXT NOT NULL,
     NEIGHBORHOOD VARCHAR NOT NULL,
	 BUILDING_CLASS_CATEGORY VARCHAR NOT NULL,
	 NUMBER_OF_SALES INT NOT NULL,
	 MINIMUM_SALE_PRICE INT NOT NULL,
	 AVERAGE_SALE_PRICE INT NOT NULL,
	 MEDIAN_SALE_PRICE INT NOT NULL,
	 MAXIMUM_SALE_PRICE INT NOT NULL
);


CREATE TABLE manhattan_sales_prices (
     BOROUGH TEXT NOT NULL,
     NEIGHBORHOOD VARCHAR NOT NULL,
	 BUILDING_CLASS_CATEGORY VARCHAR NOT NULL,
	 NUMBER_OF_SALES INT NOT NULL,
	 MINIMUM_SALE_PRICE INT NOT NULL,
	 AVERAGE_SALE_PRICE INT NOT NULL,
	 MEDIAN_SALE_PRICE INT NOT NULL,
	 MAXIMUM_SALE_PRICE INT NOT NULL
);


CREATE TABLE queens_sales_prices (
     BOROUGH TEXT NOT NULL,
     NEIGHBORHOOD VARCHAR NOT NULL,
	 BUILDING_CLASS_CATEGORY VARCHAR NOT NULL,
	 NUMBER_OF_SALES INT NOT NULL,
	 MINIMUM_SALE_PRICE INT NOT NULL,
	 AVERAGE_SALE_PRICE INT NOT NULL,
	 MEDIAN_SALE_PRICE INT NOT NULL,
	 MAXIMUM_SALE_PRICE INT NOT NULL
);


CREATE TABLE staten_island_sales_prices (
     BOROUGH TEXT NOT NULL,
     NEIGHBORHOOD VARCHAR NOT NULL,
	 BUILDING_CLASS_CATEGORY VARCHAR NOT NULL,
	 NUMBER_OF_SALES INT NOT NULL,
	 MINIMUM_SALE_PRICE INT NOT NULL,
	 AVERAGE_SALE_PRICE INT NOT NULL,
	 MEDIAN_SALE_PRICE INT NOT NULL,
	 MAXIMUM_SALE_PRICE INT NOT NULL
);
