CREATE TABLE bronx_annual_sales20 (
	YEAR INT NOT NULL,
	BOROUGH	VARCHAR NOT NULL,
	NEIGHBORHOOD VARCHAR NOT NULL,
	BUILDING_CLASS_CATEGORY	VARCHAR,
	BUILDING_CLASS_AT_PRESENT VARCHAR,
	ADDRESS	TEXT NOT NULL,
	TOTAL_UNITS	INT,
	GROSS_SQ_FT	INT,
	SALE_PRICE INT 
);

CREATE TABLE brooklyn_annual_sales20 (
	YEAR INT NOT NULL,
	BOROUGH	VARCHAR NOT NULL,
	NEIGHBORHOOD VARCHAR NOT NULL,
	BUILDING_CLASS_CATEGORY	VARCHAR,
	BUILDING_CLASS_AT_PRESENT VARCHAR,
	ADDRESS	TEXT NOT NULL,
	TOTAL_UNITS	INT,
	GROSS_SQ_FT	INT,
	SALE_PRICE INT 
);

CREATE TABLE manhattan_annual_sales20 (
	YEAR INT NOT NULL,
	BOROUGH	VARCHAR NOT NULL,
	NEIGHBORHOOD VARCHAR NOT NULL,
	BUILDING_CLASS_CATEGORY	VARCHAR,
	BUILDING_CLASS_AT_PRESENT VARCHAR,
	ADDRESS	TEXT NOT NULL,
	TOTAL_UNITS	INT,
	GROSS_SQ_FT	INT,
	SALE_PRICE INT  
);
	
CREATE TABLE queens_annual_sales20 (
	YEAR INT NOT NULL,
	BOROUGH	VARCHAR NOT NULL,
	NEIGHBORHOOD VARCHAR NOT NULL,
	BUILDING_CLASS_CATEGORY	VARCHAR,
	BUILDING_CLASS_AT_PRESENT VARCHAR,
	ADDRESS	TEXT NOT NULL,
	TOTAL_UNITS	INT,
	GROSS_SQ_FT	INT,
	SALE_PRICE INT 
);

CREATE TABLE staten_island_annual_sales20 (
	YEAR INT NOT NULL,
	BOROUGH	VARCHAR NOT NULL,
	NEIGHBORHOOD VARCHAR NOT NULL,
	BUILDING_CLASS_CATEGORY	VARCHAR,
	BUILDING_CLASS_AT_PRESENT VARCHAR,
	ADDRESS	TEXT NOT NULL,
	TOTAL_UNITS	INT,
	GROSS_SQ_FT	INT,
	SALE_PRICE INT 
);




